# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProejctStatus',
        ),
    ]
