# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_team_user_work_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField()),
                ('latest_view_date', models.DateField()),
                ('viewed_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.team')),
            ],
        ),
        migrations.CreateModel(
            name='project_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField()),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='team_recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.BigIntegerField()),
                ('add_date', models.DateField()),
                ('recommended_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.team')),
            ],
        ),
        migrations.CreateModel(
            name='user_recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.BigIntegerField()),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='work_experience',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='user_recommendation',
            name='recommended_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_profile.user'),
        ),
        migrations.AddField(
            model_name='user_recommendation',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user'),
        ),
        migrations.AddField(
            model_name='team_recommendation',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user'),
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user'),
        ),
        migrations.AddField(
            model_name='project_interest',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user'),
        ),
        migrations.AddField(
            model_name='profile_view',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.user'),
        ),
    ]
